# Generated by Django 4.2 on 2023-04-27 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transportation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarexception",
            options={"default_related_name": "calendar_exception_set"},
        ),
        migrations.AlterModelOptions(
            name="patternstop",
            options={"default_related_name": "pattern_stop_set"},
        ),
    ]
