# Generated by Django 4.2 on 2023-05-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transportation", "0002_alter_calendarexception_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patternstop",
            constraint=models.UniqueConstraint(
                fields=("pattern", "index"), name="Pattern and stop sequence unique"
            ),
        ),
    ]
