# Generated by Django 4.2 on 2023-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transportation", "0003_patternstop_pattern_and_stop_sequence_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="calendarexception",
            constraint=models.UniqueConstraint(
                fields=("calendar", "day"),
                name="Only one CalendarException for a calendar on a given day",
            ),
        ),
    ]
