# Generated by Django 4.2.1 on 2023-05-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transportation",
            "0004_calendarexception_only_one_calendarexception_for_a_calendar_on_a_given_day",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
