# Generated by Django 4.2.1 on 2023-05-22 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transportation", "0005_import"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="import",
            options={"verbose_name_plural": " Imports"},
        ),
    ]
