# Generated by Django 4.2.1 on 2023-05-22 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transportation", "0008_alter_import_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="import",
            name="filename",
        ),
    ]
