# Generated by Django 4.2.1 on 2023-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transportation", "0009_remove_import_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="import",
            name="filename",
            field=models.CharField(default="zipfile", max_length=100),
        ),
    ]
