# Generated by Django 4.2.1 on 2023-05-23 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transportation", "0010_import_filename"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Import",
        ),
    ]
