from typing import TYPE_CHECKING

from django.db import models

if TYPE_CHECKING:
    from django.db.models import Manager

    from .line import Line


class Agency(models.Model):
    name = models.CharField(max_length=64)
    website = models.CharField(max_length=128)
    timezone = models.CharField(max_length=64, null=True, blank=True)
    telephone = models.CharField(max_length=32, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Agencies"

    # Attributes generated by Django, but which need explicit hints for type checker:
    id: int
    pk: int
    line_set: "Manager[Line]"
